plugin: aws_ec2
regions:
  - ap-south-1

keyed_groups:
  - key: tags.Name
    prefix: ""

filters:
  tag:Name:
    - "jenkins-master"
    - "jenkins-slave"
    - "kubemaster"
    - "kubenode1"


compose:
  ansible_host: public_ip_address
